Add controllers
SudarikovYaroslav/java-shareit pull request #2
Opened 2022-08-12 09:54 UTC by SudarikovYaroslav

В качестве некоторых переменных pojo объектов, а также некоторых параметров методов контроллеров и маперов намеренно использую ссылочные обёртки для примитивов, потому, что очень важно, чтобы эти значения могли быть null.

Это связано с тем, что значения для этих переменных приходят с фронтенда и могут прийти null, и для корректной работы репозиториев нужно, чтобы эти значения так и остались null, а не инициализировались по умолчанию при создании соответствующих pojo объектов. Это особенно критично для значений типа boolean.

2022-08-14 08:02 UTC, SudarikovYaroslav commented
Действительно, проект приватный был.
Не обратил внимание, всегда заготовки публичные, даже в голову не пришло проверить((

2022-08-15 12:29 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +package ru.practicum.shareit.item.controller;
при таком способе организации классов отдельные пакеты для сервисов, контроллеров и стораджей обычно не делают, потому что предполагается, что у фичи не будет нескольких контроллеров и тд
 
 но можно оставить

2022-08-15 12:29 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestBody ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") Long userId) {
хедер стоит вынести в константу

2022-08-15 12:32 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +    public ItemDto mapItemToItemDto(Item item) {
можно назвать методы toDto и toModel, обычно для мапперов это привычные название

2022-08-15 12:35 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/service/UserMapper.java
> +        return new User(NULL_USER_ID, userDto.getName(), userDto.getName());
лучше не зашивать всегда null для userId при маппинге, а прокидывать userId как второй аргумент метода
там, где его неоткуда взять - в аргумент подставлять null

2022-08-15 12:36 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userDao.findUserByID(userId);
camelCase: `findUserById`

2022-08-15 12:37 UTC, makholin requested changes
Хорошая работа
Нужно исправить замечания

2022-08-15 23:01 UTC, makholin approved these changes
Работа принята

2022-08-16 05:42 UTC, merged