Add bookings
SudarikovYaroslav/java-shareit pull request #4
Opened 2022-08-30 13:21 UTC by SudarikovYaroslav

2022-08-31 13:42 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>      private BookingStatus status;
если данные в колонке бд будут мапиться из енума, то ограничение максимальной длины не очень не нужно
если кто-то добавит значение, которого нет в енуме, то приложение будет падать, когда будет вычитывать данные

2022-08-31 13:48 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toResponseDto(bookingRepository.save(booking), booking.getBooker(), item);
сохранение и маппинг лучше разделить на 2 отдельных действия (на разных строчках)
иначе другой разработчик может не заметить сохранения внутри

2022-08-31 13:51 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        State status = tryDetectState(state);
переменную тоже нужно назвать state как тип, иначе возникает путаница с BookingStatus

2022-08-31 13:53 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private BookingStatus detectStatus(Boolean b) {
лучше `convertToStatus(boolean approved)`

2022-08-31 13:56 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    @JoinColumn(name = "item_id")
для item_id можно использовать константу из другого класса

2022-08-31 13:57 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDetailedDto createComment(@Validated({Update.class}) @RequestBody CommentCreateDto commentDto,
классы лучше назвать `DetailedComment` и `DetailedCommentDto`

2022-08-31 13:59 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDetailedDto.java
> +    private String authorName;
может лучше использовать id юзера, который оставляет коммент?

2022-08-31 14:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +    List<Comment> findByItem_Id(Long itemId);
название должно быть в camelCase: `findByItemId`
jpa должно такое распарсить

2022-08-31 14:04 UTC, makholin requested changes
нужно исправить замечания

2022-08-31 17:29 UTC, SudarikovYaroslav commented on src/main/java/ru/practicum/shareit/item/dto/CommentDetailedDto.java
> +    private String authorName;
Я делал все Dto на основе тестов, т.е. в них все поля, такие, как тесты в postman проверяют. Собственно поэтому у меня тут и authorName, т.к. тест именно имя проверяет. 

Как я понял, тут предполагается, что этот dto уже пользователю на фронт прилетит. Поэтому наверное подразумевают, что пользователь должен, в приложении например, увидеть имя пользователя, который комментарий написал, а не какой у него id в БД

2022-09-02 08:15 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDetailedDto.java
> +    private String authorName;
понял, тогда да, все правильно

2022-09-02 08:20 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toResponseDto(bookingRepository.save(booking), booking.getBooker(), item);
нужно разделить на два отдельных действия

```
repository.save(booking);
return mapper.toDto(booking);
```

2022-09-02 08:23 UTC, makholin approved these changes
Работа принята

2022-09-02 09:10 UTC, merged